import random

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
user = int(input("'Type' \n1 : rock\n2 : paper\n3 : scissors \n"))
print('''----------------- For Users ---------------------------- ''')
random_value = random.randint(1,3)

if user == 1:
    print(rock) 
elif user == 2:
    print(paper)
elif user == 3:
    print(scissors)
print('''------------------ generated by Computer ---------------''')
store_random = random_value
print(store_random)
if store_random == 1:
    print(rock)
elif store_random == 2:
    print(paper)
elif store_random == 3:
    print(scissors)

if user == 1 and store_random == 1:
    print("Same")
elif user == 1 and store_random == 2:
    print("You loss")
elif user== 1 and store_random ==3:
    print("you won")
if user == 2 and store_random ==1:
    print("You won")
elif user == 2 and store_random == 2:
    print("same")
elif user == 2 and store_random ==3:
    print("You Loss")
if user == 3 and store_random ==1:
    print("You loss")
elif user == 3 and store_random == 2:

    print("You won")
elif user == 3 and store_random ==3:
    print("Same")






